<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml">
	<head>
		<meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
		<title><?= PROYECTO_NOMBRE ?></title>
		<link rel="shortcut icon" href="<?= PUBLIC_PATH ?>favicon.ico" type="image/x-icon" /> 
		<meta http-equiv="imagetoolbar" content="no" />
		
		<?= stylesheet_link_tag('style') ?>
		
		<?= View::partial("jquery",false,'template: ui-darkness, version: 13'); ?>
        
        <?= javascript_include_tag('kumbia/validations') ?>
		<?= javascript_include_tag('amecasoft') ?>
		<?= javascript_include_tag('bootstrap') ?>
		<style type="text/css">
		    body{
		        padding-top: 25px;
		    }
		</style>
		<?= stylesheet_link_tag('bootstrap') ?>
	    <?= stylesheet_link_tag('bootstrap-responsive') ?>
	    <?= stylesheet_link_tag('bootswatch') ?>
	
	    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
	    <!--[if lt IE 9]>
	      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	    <![endif]-->
        
	</head>
	<body>
		<?php View::content();?>		
	</body>
</html>
