<?php Load::lib("formulario"); ?>
<?= isset($mensaje) ? '<div class="alert alert-success" style="margin: 0px auto 30px; width: 420px;">' . $mensaje . "</div>" : "" ?>
<div class="container">
	<?= Formulario::inicio("pedidos/modificar","consulta","class: form-horizontal well","style: margin: 0px auto 0px; width: 420px;") ?>
	<?= Formulario::oculto("id", $pedido -> id) ?>
		<fieldset>
			<legend>Información del Pedido</legend>
			<div class="control-group">
	            <label class="control-label">Orden de Venta: </label>
	            <div class="controls">
	           		<?= Formulario::mayusculas("crm_numero",$pedido -> crm_numero) ?>
	            </div>
	        </div>
	        <div class="control-group">
	            <label class="control-label">Nombre: </label>
	            <div class="controls">
	           		<?= Formulario::texto("nombre",$pedido -> nombre) ?>
	            </div>
	        </div>
	        <div class="control-group">
	            <label class="control-label">Total: </label>
	            <div class="controls">
	           		<?= Formulario::texto("total",$pedido -> total) ?>
	            </div>
	        </div>
	        <div class="control-group">
	            <label class="control-label">Anticipo: </label>
	            <div class="controls">
	           		<?= Formulario::texto("anticipo",$pedido -> anticipo) ?>
	            </div>
	        </div>
	        <div class="control-group">
	            <label class="control-label">Saldo: </label>
	            <div class="controls">
	           		<?= Formulario::texto("saldo",$pedido -> saldo) ?>
	            </div>
	        </div>
	        <div class="form-actions" align="right">
	        	<?= Formulario::reset("Cancelar","style: font-weight: bold;","class: btn btn-danger") ?>
	        	<?= Formulario::submit("Modificar","style: font-weight: bold;","class: btn btn-success") ?>
          	</div>
		</fieldset>
	<?= Formulario::fin() ?>
</div>