<?php Load::lib("formulario"); ?>
<?= isset($mensaje) ? '<div class="alert alert-success" style="margin: 0px auto 30px; width: 420px;">' . $mensaje . "</div>" : "" ?>
<div class="container">
	<?= Formulario::inicio("disenadores/modificar","consulta","class: form-horizontal well","style: margin: 0px auto 0px; width: 420px;") ?>
	<?= Formulario::oculto("id", $disenador -> id) ?>
		<fieldset>
			<legend>Información del Diseñador</legend>
			<div class="control-group">
	            <label class="control-label">Cliente: </label>
	            <div class="controls">
	           		<?= Formulario::mayusculas("nombre",$disenador -> nombre) ?>
	            </div>
	        </div>
	        <div class="control-group">
	            <label class="control-label">Correo Electrónico: </label>
	            <div class="controls">
	           		<?= Formulario::texto("correo",$disenador -> correo) ?>
	            </div>
	        </div>
	        <div class="control-group">
	            <label class="control-label">Usuario: </label>
	            <div class="controls">
	           		<?= Formulario::texto("usuario",$disenador -> usuario) ?>
	            </div>
	        </div>
	        <div class="control-group">
	            <label class="control-label">Contraseña: </label>
	            <div class="controls">
	           		<?= Formulario::password("password","**********") ?>
	            </div>
	        </div>
	        <div class="control-group">
	            <label class="control-label">Activo: </label>
	            <div class="controls">
	           		<?php $sino = array("SI" => "SI","NO" => 	"NO"); ?>
					<?= Formulario::select("activo",$sino,$disenador -> activo) ?>
	            </div>
	        </div>
	        <div class="form-actions" align="right">
	        	<?= Formulario::reset("Cancelar","style: font-weight: bold;","class: btn btn-danger") ?>
	        	<?= Formulario::submit("Modificar","style: font-weight: bold;","class: btn btn-success") ?>
          	</div>
		</fieldset>
	<?= Formulario::fin() ?>
</div>