<?php Load::lib("html") ?>
<?= isset($mensaje) ? '<div class="alert alert-error" style="margin: 0px auto 30px; width: 90%;">' . $mensaje . "</div>" : "" ?>
<div class="container">
	<?php if($pedidos){?>
		<table border="1" cellpadding="5" cellspacing="1" class="table table-bordered table-striped">
		<tr>
			<th>Proyecto</th>
			<th>Tipo</th>
			<th>Diseñador</th>
			<th>Acciones</th>			
		</tr>
		<?php if($pedidos) foreach($pedidos as $pedido){ ?>
			<script>
				function confirmar<?= $pedido -> id ?>(){
					if(<?= $pedido -> descargado > 0 ? "false" : "true" ?>){
						alert("¡¡Al menos deberías descargar el archivo!!\n\nSi ya lo hiciste, por favor recarga esta página.");
						return false;
					}
				}
			</script>
		<tr>
			<td><?= $pedido -> crm_numero ?></td>
			<td><?= $pedido -> tipo_diseno ?> <?= $pedido -> diseno_tipo ?></td>
			<td>
				<?= ($pedido -> estado == "ASIGNADO" || $pedido -> estado == "DISEÑO") && Disenador::consultar($pedido -> disenador_id) ? Disenador::consultar($pedido -> disenador_id) -> nombre : "Esperando..." ?>
			</td>
			<td style="text-align: center">
				<?php if($pedido -> estado == "DISPONIBLE"){ ?>
					<?= Html::link("disenadores/consulta/".$pedido -> crm_cifrado, "Solicitar Trabajo") ?>
				<?php } else { ?>
					<?= Html::link("disenadores/descargar/".$pedido -> crm_cifrado,"BAJAR") ?>
					<?php if($pedido -> estado == "DISEÑO"){ ?>
						
					<?php } else { ?>
						| <?= Html::link("disenadores/trabajo/".$pedido -> crm_cifrado."/OK","OK", "onclick: return confirmar".$pedido -> id."();") ?> | 
						<?= Html::link("disenadores/trabajo/".$pedido -> crm_cifrado."/NOOK","NO OK", "onclick: return confirmar".$pedido -> id."();") ?>
					<?php } ?>
				<?php } ?>
			</td>
		</tr>
		<?php } ?>
	</table>	
	<?php } else{ ?>
		No hay trabajos disponibles por el momento.	
	<?php } ?>	
</div>
<?php if($pedido -> estado == "DISEÑO"){ ?>
<?= Load::lib("formulario") ?>
<?= Load::lib("mensajes") ?>
<style type="text/css">
	body{
		font-size: 12px;
	}
	.attach {
		width: 150px;
		font-size: 12px;
		background-color: white;
		color: black;
	}
	
	.attach img {
		float:left;
	}
	
	#SWFUpload_0 {
		width: 150px;
	}
</style>
<?= javascript_include_tag('jquery.uploadify.min') ?>
<?= stylesheet_link_tag('uploadify/uploadify') ?>
<script type="text/javascript">
	<?php $timestamp = time();?>
	$(function() {
		$('#file_upload').uploadify({
			'buttonText' : '<div class=attach><img src=/diseno/img/uploadify/attachment.png ></img><p>Adjuntar Archivo</p></div>',
			'multi': false,
			'formData'     : {
				'timestamp' : '<?php echo $timestamp;?>',
				'token'     : '<?php echo md5('unique_salt' . $timestamp);?>',
				'pedido'	: '<?= $pedido -> crm_numero ?>'
			},
			'onUploadStart' : function(file){
				
			},
			'onUploadSuccess' : function(file, data, response){
				var res = jQuery.parseJSON(data);
				
				if(res.status == "ok"){
					
					$("#name1").html(res.file);
					
					$('#temporal').load('<?= get_kumbia_url("uploader/archivo") ?>/'+res.file+'/'+res.msg);
					
					setTimeout( function() {
						if(res.numero > 1){
							$("#mensaje").append($('#temporal').html());
						}
						else{
							$("#mensaje").html($('#temporal').html());
						}
					}, 2000 );
					
					$('#boton').show();
					
					$('#file_upload').hide();
					
					$('#archivo').val(res.file);
					
				}
				else{
					
					$('#modal-body').load('<?= get_kumbia_url("uploader/error") ?>/'+res.file+'/'+res.error);
					
					setTimeout( function() {
						$('#errorModal').modal({
						  keyboard: true
						});
					}, 1000 );
				}
				
				confirmar();
    		},
			'swf'      : '<?= PUBLIC_PATH ?>uploadify.swf',
			'uploader' : '<?= PUBLIC_PATH ?>uploadify.php'
		});
		
		$('#boton').hide();
	});
	
	function confirmar(){
		var x = -1;
		
		$('#myModal').modal({
		  keyboard: true
		})
	}
	
</script>
<script>
$(document).ready(function(){
   $("#revisar").click(function(evento){
      evento.preventDefault();
      
      $('#boton').hide();
	  $('#file_upload').show();
	  
	  $("#temporal").load("<?= APLICACION_PATH ?>uploader/cancelar/<?= $pedido -> crm_numero ?>");
	  
	  location.reload();
   });
})
</script>
<div class="container" style="font-size: 14px;">
	<div class="row">
		<div class="span3"></div>
		<div class="span6" align="center">
			<?= Formulario::inicio("#",true,"class: form-horizontal well","style: margin: auto; height: 150px;") ?>
				<fieldset>
					<legend style="font-size: 24px; color: yellow;">SUBIR ARCHIVOS PARA IMPRESIÓN</legend>
					<table border="0" cellpadding="5" style="width: 100%">
						<tr>
							<td colspan="2" align="center" id="filex">
								<input id="file_upload" name="file_upload" type="file" multiple="false">
							</td>
						</tr>
					</table>
				</fieldset>
			<?= Formulario::fin() ?>
		</div>
		<div class="span3"></div>
	</div>
</div>
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="font-size: 14px;">
	<?= Formulario::inicio("uploader/terminar","class: form-horizontal well","style: margin: auto;") ?>
		<?= Formulario::oculto("pedido", $pedido -> id) ?>
	 <div class="modal-header" align="center">
	 	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
	 	<h3 id="myModalLabel"><?= Mensajes::consultar("DISENO_CASI_LISTO") ?></h3>
	 </div>
	 <div class="modal-body" align="justify">
	 	<?= Mensajes::consultar("TERMINAR_PREPRENSA") ?>
	 </div>
	  <div class="modal-footer">
	    <button class="btn btn-danger" id="revisar" data-dismiss="modal" aria-hidden="true">Revisar</button>
	    <button class="btn btn-success" onclick="return aceptar();">Aceptar</button>
	  </div>
	 <?= Formulario::fin() ?>
</div>
<div id="temporal" style="display: none;"></div>
<?php } ?>