<?php Load::lib("formulario"); ?>
<div class="container">
	<?= Formulario::inicio("disenadores/registrar","registro","class: form-horizontal well","style: margin: auto; width: 420px;") ?>
		<fieldset>
			<legend>Registro de Diseñador</legend>
			<div class="control-group">
	            <label class="control-label">Nombre: </label>
	            <div class="controls">
	           		<?= Formulario::mayusculas("nombre","") ?>
	            </div>
	        </div>
	        <div class="control-group">
	            <label class="control-label">Correo Electrónico: </label>
	            <div class="controls">
	           		<?= Formulario::texto("correo","") ?>
	            </div>
	        </div>
	        <div class="control-group">
	            <label class="control-label">Usuario: </label>
	            <div class="controls">
	           		<?= Formulario::texto("usuario","") ?>
	            </div>
	        </div>
	        <div class="control-group">
	            <label class="control-label">Contraseña: </label>
	            <div class="controls">
	           		<?= Formulario::password("password","") ?>
	            </div>
	        </div>
	        
	        <div class="form-actions" align="right">
	        	<?= Formulario::reset("Cancelar","style: font-weight: bold;","class: btn btn-danger") ?>
	        	<?= Formulario::submit("Registrar","style: font-weight: bold;","class: btn btn-success") ?>
          	</div>
		</fieldset>
	<?= Formulario::fin() ?>
</div>