<?php Load::lib("html") ?>
<?= isset($mensaje) ? '<div class="alert alert-success" style="margin: 0px auto 30px; width: 90%;">' . $mensaje . "</div>" : "" ?>
<div class="container">
	<table border="1" cellpadding="5" cellspacing="1" class="table table-bordered table-striped">
		<tr>
			<th>Id</th>
			<th>Nombre</th>
			<th>Usuario</th>
			<th>Contraseña</th>
			<th>Correo</th>
			<th>Activo</th>
			<th colspan="2"></th>
		</tr>
		<?php if($disenadores) foreach($disenadores as $disenador){ ?>
		<tr>
			<td><?= $disenador -> id ?></td>
			<td><?= $disenador -> nombre ?></td>
			<td><?= $disenador -> usuario ?></td>
			<td><?= $disenador -> password ?></td>
			<td><?= $disenador -> correo ?></td>
			<td><?= $disenador -> activo ?></td>
			<td style="text-align: center"><?= Html::link("disenadores/consulta/".$disenador -> id, html::imagen("miniconos/page_white_edit.png")) ?></td>
			<td style="text-align: center"><?= Html::link("disenadores/eliminar/".$disenador -> id, html::imagen("miniconos/cancel.png")) ?></td>
		</tr>
		<?php } ?>
	</table>	
</div>