<p>
	El archivo que acaba de subir (<span id="name2" style="color: yellow; font-weight: bold;"></span>) no esta convertido a curvas. No podemos imprimir un archivo de Ilustrador que no esta convertido a curvas. ¿Por qué? <a href="#">Vealo Aquí</a>
</p>
<br>
<p>
	Por favor, conviertalo a curvas y suba el archivo nuevamente.
</p>
<br>
<p align="center" style="font-size: 16px;">
	<span style="font-size: 22px; color: yellow;">¿Cómo resuelvo esto?</span>
	<br>
	<br>
	<a href="#">Vea este sencillo Instructivo</a>
	<br>
	<br>
	sobre cómo convertir su Ilustrador a Curvas
</p>
<br>
<p align="center" style="font-size: 22px; color: yellow;">
	¿Tiene Dudas?
</p>
<br>
<p align="center">
	Puede llamar al <span>3220 - 0657</span> o enviar su consulta a
	<br>
	diseno@masfolletospormenos.com.ar
</p>