<?php Load::lib("formulario"); ?>
<div class="container hero-unit" >
	<div class="row">
		<div class="span6">
			<?= Formulario::inicio("disenadores/registrar","registro","class: form-horizontal well","style: margin: auto;") ?>
				<fieldset>
					<legend>SUBIR ARCHIVOS PARA IMPRESIÓN</legend>
					<table border="0" cellpadding="5" style="width: 100%">
						<tr>
							<td align="left">
								Cliente:
							</td>
							<td align="left">
								<?= $pedido -> nombre ?>
							</td>
						</tr>
						<tr>
							<td align="left">
								Orden de Venta:
							</td>
							<td align="left">
								<?= $pedido -> crm_numero ?>
							</td>
						</tr>
						<tr>
							<td colspan="2"></td>
						</tr>
						<tr>
							<td align="left" colspan="2" style="color: yellow">
								¿Cuantas Caras tiene su Diseño?
							</td>
						</tr>
						<tr>
							<td align="left" colspan="2">
								<table border="0" cellpadding="5">
									<tr>
										<td style="vertical-align: middle;"><input type="radio" name="caras" value="2" style="margin-top: -5px;"/></td>
										<td style="vertical-align: bottom;">2 Caras distintas</td>
									</tr>
									<tr>
										<td style="vertical-align: middle;"><input type="radio" name="caras" value="2" style="margin-top: -5px;"/></td>
										<td style="vertical-align: bottom;">1 Cara, imprimir lo mismo de los dos lados.</td>
									</tr>
									<tr>
										<td style="vertical-align: middle;"><input type="radio" name="caras" value="2" style="margin-top: -5px;"/></td>
										<td style="vertical-align: bottom;">1 Cara, dejar una Cara en blanco</td>
									</tr>
								</table>
							</td>
						</tr>
						<tr>
							<td align="left" colspan="2" style="color: yellow">
								Comentarios (Opcional)
							</td>
						</tr>
						<tr>
							<td colspan="2">
								<?= Formulario::textarea("comentarios","","style: width: 500px; height: 100px;") ?>
							</td>
						</tr>
					</table>
			        <div class="form-actions" align="right">
			        	<?= Formulario::reset("Cancelar","style: font-weight: bold;","class: btn btn-danger") ?>
			        	<?= Formulario::submit("Registrar","style: font-weight: bold;","class: btn btn-success") ?>
		          	</div>
				</fieldset>
			<?= Formulario::fin() ?>
		</div>
		<div class="span6">
			<div class"row" align="justify">
				Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500, cuando un impresor (N. del T. persona que se dedica a la imprenta) desconocido usó una galería de textos y los mezcló de tal manera que logró hacer un libro de textos especimen. No sólo sobrevivió 500 años, sino que tambien ingresó como texto de relleno en documentos electrónicos, quedando esencialmente igual al original. Fue popularizado en los 60s con la creación de las hojas "Letraset", las cuales contenian pasajes de Lorem Ipsum, y más recientemente con software de autoedición, como por ejemplo Aldus PageMaker, el cual incluye versiones de Lorem Ipsum.
			</div>
		</div>
	</div>
</div>