<?php Load::lib("formulario"); ?>
<?php Load::lib("html"); ?>
<style type="text/css">
	body{
		font-size: 12px;
	}
	.attach {
		width: 150px;
		font-size: 12px;
		background-color: white;
		color: black;
	}
	
	.attach img {
		float:left;
	}
	
	#SWFUpload_0 {
		width: 150px;
	}
</style>
<?= javascript_include_tag('jquery.uploadify.min') ?>
<?= stylesheet_link_tag('uploadify/uploadify') ?>
<script type="text/javascript">
	<?php $timestamp = time();?>
	$(function() {
		$('#file_upload').uploadify({
			'buttonText' : '<div class=attach><img src=/diseno/img/uploadify/attachment.png ></img><p>Adjuntar Archivo</p></div>',
			'multi': false,
			'formData'     : {
				'timestamp' : '<?php echo $timestamp;?>',
				'token'     : '<?php echo md5('unique_salt' . $timestamp);?>',
				'pedido'	: '<?= $pedido -> crm_numero ?>'
			},
			'onUploadStart' : function(file){
				
			},
			'onUploadSuccess' : function(file, data, response){
				var res = jQuery.parseJSON(data);
				
				if(res.status == "ok"){
					
					$("#name1").html(res.file);
					
					if(res.numero > 1){
						$("#mensaje").append(res.msg);
					}
					else{
						$("#mensaje").html(res.msg);
					}
					
					$('#boton').show();
					
					<?= $tipo_folleto == "pp" ? "$('#file_upload').hide();" : "" ?>
					
					$('#archivo').val(res.file);
					
				}
				else{
					$("#name2").html(res.file);
					
					$('#myModal2').modal({
					  keyboard: true
					})
				}
    		},
			'swf'      : '<?= PUBLIC_PATH ?>uploadify.swf',
			'uploader' : '<?= PUBLIC_PATH ?>uploadify.php'
		});
		
		$('#boton').hide();
	});
	
	function confirmar(){
		var x = -1;
		
		if($("input[name='carastmp']:checked").val()==0 || $("input[name='carastmp']:checked").val()==1 || $("input[name='carastmp']:checked").val()==2){
			x = $("input[name='carastmp']:checked").val();
		}
		
		if(x == -1){
			alert("Por favor, Seleccione cuantas caras tiene su folleto."); return;
		}
		
		$('#myModal').modal({
		  keyboard: true
		})
	}
	
	function aceptar(){
		$('#caras').val($("input[name='carastmp']:checked").val());
		$('#comentarios').val($('#comentariostmp').val());
		$('#ordenventa').val(<?= $pedido -> crm_numero ?>);
		
		alert($('#caras').val());
		alert($('#comentarios').val());
		alert($('#ordenventa').val());
		alert($('#archivo').val());
	}
	
	
</script>
<script>
$(document).ready(function(){
   $("#revisar").click(function(evento){
      evento.preventDefault();
      
      $('#boton').hide();
	  $('#file_upload').show();

      $("#mensaje").load("<?= APLICACION_PATH ?>uploader/revisar/<?= $pedido -> crm_numero ?>");
   });
})
</script><?= $pedido -> diseno_estado ?>
<div class="container hero-unit" style="font-size: 14px;">
	<div class="row">
		<div class="span6">
			<?= Formulario::inicio("#",true,"class: form-horizontal well","style: margin: auto; height: 500px;") ?>
				<fieldset>
					<legend style="font-size: 24px; color: yellow;">SUBIR ARCHIVOS PARA IMPRESIÓN</legend>
					<table border="0" cellpadding="5" style="width: 100%">
						<tr>
							<td align="left">
								Cliente:
							</td>
							<td align="left">
								<?= $pedido -> nombre ?>
							</td>
						</tr>
						<tr>
							<td align="left">
								Orden de Venta:
							</td>
							<td align="left">
								<?= $pedido -> crm_numero ?>
							</td>
						</tr>
						<tr>
							<td colspan="2"></td>
						</tr>
						<tr>
							<td align="left" colspan="2" style="color: yellow">
								¿Cuantas Caras tiene su Diseño?
							</td>
						</tr>
						<tr>
							<td align="left" colspan="2">
								<table border="0" cellpadding="5">
									<tr>
										<td style="vertical-align: middle;"><input type="radio" id="carastmp" name="carastmp" value="2" style="margin-top: -5px;"/></td>
										<td style="vertical-align: bottom;">2 Caras distintas.</td>
									</tr>
									<tr>
										<td style="vertical-align: middle;"><input type="radio" id="carastmp" name="carastmp" value="1" style="margin-top: -5px;"/></td>
										<td style="vertical-align: bottom;">1 Cara, imprimir lo mismo de los dos lados.</td>
									</tr>
									<tr>
										<td style="vertical-align: middle;"><input type="radio" id="carastmp" name="carastmp" value="0" style="margin-top: -5px;"/></td>
										<td style="vertical-align: bottom;">1 Cara, dejar una Cara en blanco.</td>
									</tr>
								</table>
							</td>
						</tr>
						<tr>
							<td align="left" colspan="2" style="color: yellow">
								Comentarios (Opcional)
							</td>
						</tr>
						<tr>
							<td colspan="2">
								<?= Formulario::textarea("comentariostmp","","style: width: 500px; height: 50px;") ?>
							</td>
						</tr>
						<tr>
							<td colspan="2" align="left">
								<input id="file_upload" name="file_upload" type="file" multiple="false">
							</td>
						</tr>
					</table>
				</fieldset>
			<?= Formulario::fin() ?>
		</div>
		<div class="span6">
			<?= Formulario::inicio("#",false,"class: form-horizontal well","style: margin: auto; height: 500px;") ?>
			<div class"row" align="justify" id="mensaje" style="font-size: 14px; height: 400px; max-width: 520px;">
				<?= Mensaje::get("INICIO_UPLOADER") ?>
			</div>
			<div class="form-actions" align="right">
				<?= Formulario::boton("Registrar","return confirmar();","id: boton","class: btn btn-success") ?>
          	</div>
          	<?= Formulario::fin() ?>
		</div>
	</div>
</div>

<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="font-size: 14px;">
	<?= Formulario::inicio("pedido/upload","upload","class: form-horizontal well","style: margin: auto; height: 500px;") ?>
		<?= Formulario::oculto("caras", 2) ?>
		<?= Formulario::oculto("comentarios", "") ?>
		<?= Formulario::oculto("ordenventa", "") ?>
		<?= Formulario::oculto("archivo", "") ?>
	 <div class="modal-header" align="center">
	 	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
	 	<h3 id="myModalLabel">¡Archivo casi listo para impresión!</h3>
	 </div>
	 <div class="modal-body" align="justify">
	 	<p>Parece que el archivo <span id="name1" style="color: yellow; font-weight: bold;"></span> esta listo (OK) para impresión, de todas formas nuestro equipo de diseño le dará una segunda revisión para asegurarnos que todo esta OK.</p>
	 	<br>
	 	<p style="color: yellow; font-size: 18px;" align="center"><b style="font-size: 24px;">IMPORTANTE</b><br><br>Estos archivos se imprimirán. <br><br><span style="font-size: 14px;">No se aceptan cambios una vez que el archivo entra a impresión.</span></p>
	 	<br>
	 	<p>Recomendamos que verifique bien, que subió los archivos correctos para impresión</p>
	 	<p>¿Estás seguro que los archivos que subiste estan listos para impresión?</p>
	 </div>
	  <div class="modal-footer">
	    <button class="btn btn-danger" id="revisar" data-dismiss="modal" aria-hidden="true">Revisar</button>
	    <button class="btn btn-success" onclick="return aceptar();">Aceptar</button>
	  </div>
	 <?= Formulario::fin() ?>
</div>


<div id="myModal2" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="font-size: 14px;">
	 <div class="modal-header" align="center">
	 	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
	 	<h3 id="myModalLabel" style="color: yellow; font-weight: bold;">¡Ufa! !Paso algo con el archivo!</h3>
	 </div>
	 <div class="modal-body" align="justify">
	 	<p>El archivo que acaba de subir (<span id="name2" style="color: yellow; font-weight: bold;"></span>) no esta convertido a curvas. No podemos imprimir un archivo de Ilustrador que no esta convertido a curvas. ¿Por qué? <a href="#">Vealo Aquí</a></p>
	 	<br>
	 	<p>Por favor, conviertalo a curvas y suba el archivo nuevamente.</p>
	 	<br>
	 	<p align="center" style="font-size: 16px;"><span style="font-size: 22px; color: yellow;">¿Cómo resuelvo esto?</span><br><br><a href="#">Vea este sencillo Instructivo</a><br><br>sobre cómo convertir su Ilustrador a Curvas</p>
	 	<br>
	 	<p align="center" style="font-size: 22px; color: yellow;">¿Tiene Dudas?</p>
	 	<br>
	 	<p align="center">Puede llamar al <span>3220 - 0657</span> o enviar su consulta a <br>diseno@masfolletospormenos.com.ar</p>
	 </div>
	  <div class="modal-footer">
	    <button class="btn btn-success" id="ok" data-dismiss="modal" aria-hidden="true">Aceptar</button>
	  </div>
</div>