<?php Load::lib("formulario"); ?>
<?php Load::lib("html"); ?>
<?php Load::lib("mensajes"); ?>
<style type="text/css">
	body{
		font-size: 12px;
	}
	.attach {
		width: 150px;
		font-size: 12px;
		background-color: white;
		color: black;
	}
	
	.attach img {
		float:left;
	}
	
	#SWFUpload_0 {
		width: 150px;
	}
</style>
<?= javascript_include_tag('jquery.uploadify.min') ?>
<?= stylesheet_link_tag('uploadify/uploadify') ?>
<script type="text/javascript">
	<?php $timestamp = time();?>
	$(function() {
		$('#file_upload').uploadify({
			'buttonText' : '<div class=attach><img src=/diseno/img/uploadify/attachment.png ></img><p>Adjuntar Archivo</p></div>',
			'multi': false,
			'formData'     : {
				'timestamp' : '<?php echo $timestamp;?>',
				'token'     : '<?php echo md5('unique_salt' . $timestamp);?>',
				'pedido'	: '<?= $pedido -> crm_numero ?>'
			},
			'onUploadStart' : function(file){
				
			},
			'onUploadSuccess' : function(file, data, response){
				var res = jQuery.parseJSON(data);
				
				if(res.status == "ok"){
					
					$("#name1").html(res.file);
					
					$('#temporal').load('<?= get_kumbia_url("uploader/archivo") ?>/'+res.file+'/'+res.msg);
					
					setTimeout( function() {
						if(res.numero > 1){
							$("#mensaje").append($('#temporal').html());
						}
						else{
							$("#mensaje").html($('#temporal').html());
						}
					}, 2000 );
					
					$('#boton').show();
					
					<?= $tipo_folleto == "pp" ? "$('#file_upload').hide();" : "" ?>
					
					$('#archivo').val(res.file);
					
				}
				else{
					
					$('#modal-body').load('<?= get_kumbia_url("uploader/error") ?>/'+res.file+'/'+res.error);
					
					setTimeout( function() {
						$('#errorModal').modal({
						  keyboard: true
						});
					}, 1000 );
				}
    		},
			'swf'      : '<?= PUBLIC_PATH ?>uploadify.swf',
			'uploader' : '<?= PUBLIC_PATH ?>uploadify.php'
		});
		
		$('#boton').hide();
	});
	
	function confirmar(){
		var x = -1;
		
		if($("input[name='carastmp']:checked").val()==0 || $("input[name='carastmp']:checked").val()==1 || $("input[name='carastmp']:checked").val()==2){
			x = $("input[name='carastmp']:checked").val();
		}
		
		if(x == -1){
			alert("Por favor, Seleccione cuantas caras tiene su folleto."); return;
		}
		
		$('#myModal').modal({
		  keyboard: true
		})
	}
	
	function aceptar(){
		$('#caras').val($("input[name='carastmp']:checked").val());
		$('#comentarios').val($('#comentariostmp').val());
		$('#ordenventa').val(<?= $pedido -> crm_numero ?>);
	}
	
	
</script>
<script>
$(document).ready(function(){
   $("#revisar").click(function(evento){
      evento.preventDefault();
      
      $('#boton').hide();
	  $('#file_upload').show();

      $("#mensaje").load("<?= APLICACION_PATH ?>uploader/revisar/<?= $pedido -> crm_numero ?>");
   });
})
</script>
<script>
$(document).ready(function(){
   function terminar(){
		alert("Terminando");
   	
      evento.preventDefault();
      
      $('#myModal').hide();
	  $('#myModal2').show();

   });
})
</script>
<div class="container hero-unit" style="font-size: 14px;">
	<div class="row">
		<div class="span6">
			<?= Formulario::inicio("#",true,"class: form-horizontal well","style: margin: auto; height: 500px;") ?>
				<fieldset>
					<legend style="font-size: 24px; color: yellow;">SUBIR ARCHIVOS PARA IMPRESIÓN</legend>
					<table border="0" cellpadding="5" style="width: 100%">
						<tr>
							<td align="left">
								Cliente:
							</td>
							<td align="left">
								<?= $pedido -> nombre ?>
							</td>
						</tr>
						<tr>
							<td align="left">
								Orden de Venta:
							</td>
							<td align="left">
								<?= $pedido -> crm_numero ?>
							</td>
						</tr>
						<tr>
							<td colspan="2"></td>
						</tr>
						<tr>
							<td align="left" colspan="2" style="color: yellow">
								¿Cuantas Caras tiene su Diseño?
							</td>
						</tr>
						<tr>
							<td align="left" colspan="2">
								<table border="0" cellpadding="5">
									<tr>
										<td style="vertical-align: middle;"><input type="radio" id="carastmp" name="carastmp" value="2" style="margin-top: -5px;"/></td>
										<td style="vertical-align: bottom;">2 Caras distintas.</td>
									</tr>
									<tr>
										<td style="vertical-align: middle;"><input type="radio" id="carastmp" name="carastmp" value="1" style="margin-top: -5px;"/></td>
										<td style="vertical-align: bottom;">1 Cara, imprimir lo mismo de los dos lados.</td>
									</tr>
									<tr>
										<td style="vertical-align: middle;"><input type="radio" id="carastmp" name="carastmp" value="0" style="margin-top: -5px;"/></td>
										<td style="vertical-align: bottom;">1 Cara, dejar una Cara en blanco.</td>
									</tr>
								</table>
							</td>
						</tr>
						<tr>
							<td align="left" colspan="2" style="color: yellow">
								Comentarios (Opcional)
							</td>
						</tr>
						<tr>
							<td colspan="2">
								<?= Formulario::textarea("comentariostmp","","style: width: 500px; height: 50px;") ?>
							</td>
						</tr>
						<tr>
							<td colspan="2" align="left">
								<input id="file_upload" name="file_upload" type="file" multiple="false">
							</td>
						</tr>
					</table>
				</fieldset>
			<?= Formulario::fin() ?>
		</div>
		<div class="span6">
			<?= Formulario::inicio("#",false,"class: form-horizontal well","style: margin: auto; height: 500px;") ?>
			<div class"row" align="justify" id="mensaje" style="font-size: 14px; height: 400px; max-width: 520px;">
				<?= Mensajes::consultar("INICIO_UPLOADER",array("PRUEBA" => "RAMIRO VERA")) ?>
			</div>
			<div class="form-actions" align="right">
				<?= Formulario::boton("Registrar","return confirmar();","id: boton","class: btn btn-success") ?>
          	</div>
          	<?= Formulario::fin() ?>
		</div>
	</div>
</div>
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="font-size: 14px;">
	<?= Formulario::inicio("uploader/cargar","class: form-horizontal well","style: margin: auto;") ?>
		<?= Formulario::oculto("pedido", $pedido -> id) ?>
		<?= Formulario::oculto("caras", 2) ?>
		<?= Formulario::oculto("comentarios", "") ?>
		<?= Formulario::oculto("ordenventa", "") ?>
		<?= Formulario::oculto("archivo", "") ?>
		<?= Formulario::oculto("tipo_folleto", $tipo_folleto) ?>
	 <div class="modal-header" align="center">
	 	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
	 	<h3 id="myModalLabel"><?= Mensajes::consultar("DISENO_CASI_LISTO") ?></h3>
	 </div>
	 <div class="modal-body" align="justify">
	 	<?= Mensajes::consultar("DISENO_REVISION") ?>
	 </div>
	  <div class="modal-footer">
	    <button class="btn btn-danger" id="revisar" data-dismiss="modal" aria-hidden="true">Revisar</button>
	    <button class="btn btn-success" onclick="return aceptar();">Aceptar</button>
	  </div>
	 <?= Formulario::fin() ?>
</div>
<div id="errorModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="font-size: 14px;">
	<div class="modal-header" align="center">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
			x
		</button>
		<h3 id="myModalLabel" style="color: yellow; font-weight: bold;"><?= Mensajes::consultar("TITULO_ERROR_ARCHIVO") ?></h3>
	</div>
	<div id="modal-body" class="modal-body" align="justify"></div>
	<div class="modal-footer">
		<button class="btn btn-success" id="ok" data-dismiss="modal" aria-hidden="true">
			Aceptar
		</button>
	</div>
</div>
<div id="myModal2" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="font-size: 14px;">
	<div class="modal-header" align="center">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
			x
		</button>
		<h3 id="myModalLabel" style="color: yellow; font-weight: bold;"><?= Mensajes::consultar("TITULO_CARGADO") ?></h3>
	</div>
	<div id="modal-body2" class="modal-body2" align="justify"></div>
	<div class="modal-footer">
		<button class="btn btn-success" id="ok" data-dismiss="modal" aria-hidden="true" onclick="terminar()">
			Aceptar
		</button>
	</div>
</div>
<div id="temporal" style="display: none;"></div>
