<!DOCTYPE HTML>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>UploadiFive Test</title>
<?= stylesheet_link_tag('uploadify/estilos') ?>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<?= javascript_include_tag('jquery.uploadify.min') ?>
<?= stylesheet_link_tag('uploadify/uploadify') ?>
<style type="text/css">
body {
	font: 13px Arial, Helvetica, Sans-serif;
}
</style>
</head>

<body>
	<form enctype="multipart/form-data">
		<div id="queue"></div>
		<input id="file_upload" name="file_upload" type="file" multiple="true">
	</form>
	<script type="text/javascript">
		<?php $timestamp = time();?>
		$(function() {
			$('#file_upload').uploadify({
				'buttonText' : '<div class=attach><img src=/diseno/img/uploadify/attachment.png ></img><p>Adjuntar Archivo</p></div>',
				'formData'     : {
					'timestamp' : '<?php echo $timestamp;?>',
					'token'     : '<?php echo md5('unique_salt' . $timestamp);?>'
				},
				'onUploadStart' : function(file){
					
				},
				'onUploadSuccess' : function(file, data, response){
					var res = jQuery.parseJSON(data);
					
					$("#mensaje").html(res.msg);
        		},
				'swf'      : '<?= PUBLIC_PATH ?>uploadify.swf',
				'uploader' : '<?= PUBLIC_PATH ?>uploadify.php'
			});
		});
	</script><br><br><br>
	<div id="mensaje"></div>
</body>
</html>