<?php Load::lib("formulario"); ?>
<?= isset($mensaje) ? '<div class="alert alert-success" style="margin: 0px auto 30px; width: 705px;">' . $mensaje . "</div>" : "" ?>
<div class="container">
	<?= Formulario::inicio("mensajes/modificar","consulta","class: form-horizontal well","style: margin: 0px auto 0px; width: 705px;") ?>
	<?= Formulario::oculto("id", $mensajes -> id) ?>
		<fieldset>
			<legend>Modificar Mensaje</legend>
			<div class="control-group">
	            <label class="control-label">Codigo: </label>
	            <div class="controls">
	           		<?= $mensajes -> codigo ?>
	            </div>
	        </div>
	        <div class="control-group">
	            <label class="control-label">Mensaje: </label>
	            <div class="controls">
	           		<?= Formulario::richtext("mensaje", $mensajes -> mensaje, 500, 400) ?>
	            </div>
	        </div>
	        <div class="form-actions" align="right">
	        	<?= Formulario::submit("Modificar","style: font-weight: bold;","class: btn btn-success") ?>
          	</div>
		</fieldset>
	<?= Formulario::fin() ?>	
	
</div>